In [31]:
%pip install "ray[default]"
%pip install python-dotenv

Requirement already satisfied: ray[default] in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (2.55.1)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (1.1.2)
Requirement already satisfied: filelock in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (3.29.1)
Requirement already satisfied: jsonschema in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (4.26.0)
Requirement already satisfied: pyyaml in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (6.0.3)
Requirement already satisfied: requests in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (2.34.2)
Requirement already satisfied: protobuf>=3.20.3 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (6.33.6)
Requirement already satisfied: packaging>=24.2 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (26.2)
Requirement already satisfied: click>=7.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (8.4.1)
Requirement already satisfied: virtualenv!=20.21.1,>=20.0.24 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (21.4.2)
Requirement already satisfied: grpcio>=1.42.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (1.81.0)
Requirement already satisfied: prometheus_client>=0.7.1 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (0.25.0)
Requirement already satisfied: smart_open in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (7.6.1)
Requirement already satisfied: opencensus in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (0.11.4)
Requirement already satisfied: colorful in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (0.5.8)
Requirement already satisfied: opentelemetry-proto in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (1.42.1)
Requirement already satisfied: opentelemetry-sdk>=1.30.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (1.42.1)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (2.13.4)
Requirement already satisfied: aiohttp_cors in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (0.8.1)
Requirement already satisfied: aiohttp>=3.13.3 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (3.14.1)
Requirement already satisfied: py-spy>=0.2.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (0.4.2)
Requirement already satisfied: opentelemetry-exporter-prometheus in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from ray[default]) (0.63b1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from aiohttp>=3.13.3->ray[default]) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from aiohttp>=3.13.3->ray[default]) (4.15.0)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from aiohttp>=3.13.3->ray[default]) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from aiohttp>=3.13.3->ray[default]) (26.1.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from aiohttp>=3.13.3->ray[default]) (2.6.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from aiohttp>=3.13.3->ray[default]) (5.0.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from aiohttp>=3.13.3->ray[default]) (1.8.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from aiohttp>=3.13.3->ray[default]) (1.24.2)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from aiohttp>=3.13.3->ray[default]) (6.7.1)
Requirement already satisfied: colorama in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from click>=7.0->ray[default]) (0.4.6)
Requirement already satisfied: opentelemetry-semantic-conventions==0.63b1 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from opentelemetry-sdk>=1.30.0->ray[default]) (0.63b1)
Requirement already satisfied: opentelemetry-api==1.42.1 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from opentelemetry-sdk>=1.30.0->ray[default]) (1.42.1)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[default]) (2.46.4)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[default]) (0.7.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[default]) (0.4.2)
Requirement already satisfied: python-discovery>=1.4 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from virtualenv!=20.21.1,>=20.0.24->ray[default]) (1.4.0)
Requirement already satisfied: distlib<1,>=0.3.7 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from virtualenv!=20.21.1,>=20.0.24->ray[default]) (0.4.2)
Requirement already satisfied: platformdirs<5,>=3.9.1 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from virtualenv!=20.21.1,>=20.0.24->ray[default]) (4.10.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from jsonschema->ray[default]) (0.30.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from jsonschema->ray[default]) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from jsonschema->ray[default]) (0.37.0)
Requirement already satisfied: six~=1.16 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from opencensus->ray[default]) (1.17.0)
Requirement already satisfied: opencensus-context>=0.1.3 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from opencensus->ray[default]) (0.1.3)
Requirement already satisfied: google-api-core<3.0.0,>=1.0.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from opencensus->ray[default]) (2.31.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from requests->ray[default]) (2026.5.20)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from requests->ray[default]) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from requests->ray[default]) (2.7.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from requests->ray[default]) (3.18)
Requirement already satisfied: wrapt in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from smart_open->ray[default]) (2.2.1)
Requirement already satisfied: proto-plus<2.0.0,>=1.24.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (1.28.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (2.53.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (1.75.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (48.0.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (2.0.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (0.6.3)
Requirement already satisfied: pycparser in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (3.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: python-dotenv in c:\users\asus\onedrive\desktop\mlops\my-first-mlops-project\venv\lib\site-packages (1.2.2)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [32]:
import os 
import ray

In [33]:
import sys; sys.path.append("..")
import warnings; warnings.filterwarnings("ignore")
from dotenv import load_dotenv; load_dotenv()
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [34]:
if ray.is_initialized():
    ray.shutdown()
ray.init()

2026-06-15 22:39:50,459	INFO worker.py:2003 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265

RayContext(dashboard_url='127.0.0.1:8265', python_version='3.10.11', ray_version='2.55.1', ray_commit='237c2455ebb1ea15a32dd9e1fdeb2d617badc37f')

In [35]:
ray.cluster_resources()

{'object_store_memory': 1316841062.0,
 'GPU': 1.0,
 'memory': 3072629146.0,
 'accelerator_type:G': 1.0,
 'node:127.0.0.1': 1.0,
 'node:__internal_head__': 1.0,
 'CPU': 16.0}

In [36]:
num_workers = 3
resources_per_worker={"CPU": 4, "GPU": 0.25}

In [37]:
import os
from pathlib import Path

if os.path.exists("/efs"):
    EFS_DIR = f"/efs/shared_storage/MY-FIRST-MLOPS-PROJECT/{os.environ.get('Eva', 'default_user')}"
else:    
    EFS_DIR = str(Path(os.getcwd()).parent / "local_storage")
    os.makedirs(EFS_DIR, exist_ok=True)

print(f"Current active storage directory: {EFS_DIR}")

Current active storage directory: /efs/shared_storage/MY-FIRST-MLOPS-PROJECT/default_user

In [38]:
import pandas as pd

In [39]:
dataset = "https://raw.githubusercontent.com/evasim/my-first-MLOPS-project/refs/heads/main/data/raw_dataset.csv"
df = pd.read_csv(dataset)
df.head()

                                                text  label
0  Wall St. Bears Claw Back Into the Black (Reute...      2
1  Carlyle Looks Toward Commercial Aerospace (Reu...      2
2  Oil and Economy Cloud Stocks' Outlook (Reuters...      2
3  Iraq Halts Oil Exports from Main Southern Pipe...      2
4  Oil prices soar to all-time record, posing new...      2

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
df.label.value_counts()

label
2    30000
3    30000
1    30000
0    30000
Name: count, dtype: int64

In [42]:
test_size = 0.2 
train_df, val_df = train_test_split(df, stratify=df.label, test_size=test_size, random_state=42)

In [43]:
train_df.label.value_counts()

label
1    24000
3    24000
0    24000
2    24000
Name: count, dtype: int64

In [44]:
val_df.label.value_counts() * int((1 - test_size) / test_size)

label
2    24000
1    24000
0    24000
3    24000
Name: count, dtype: int64

In [45]:
from collections import Counter 
import matplotlib.pyplot as plt 
import seaborn as sns; sns.set_theme()
import warnings; warnings.filterwarnings("ignore")
from wordcloud import WordCloud, STOPWORDS

In [46]:
tags = Counter(df.label)
tags.most_common()

[(2, 30000), (3, 30000), (1, 30000), (0, 30000)]

In [47]:
import json 
import nltk 
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re

In [48]:
nltk.download("stopwords")
words = stopwords.words("english")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [49]:
df.head()

                                                text  label
0  Wall St. Bears Claw Back Into the Black (Reute...      2
1  Carlyle Looks Toward Commercial Aerospace (Reu...      2
2  Oil and Economy Cloud Stocks' Outlook (Reuters...      2
3  Iraq Halts Oil Exports from Main Southern Pipe...      2
4  Oil prices soar to all-time record, posing new...      2

In [50]:
def clean_text(text, stopwords=words):
    # change every words into lower case
    text = text.lower()

    # removing stopwords such as "is", "the" and so on
    pattern = re.compile(r'\b(' + r"|".join(words)+ r")\b\s*")
    text = pattern.sub('', text)

    text = re.sub(r"([!\"'#$%&()*\+,-./:;<=>?@\\\[\]^_`{|}~])", r" \1 ", text) # add space 
    text = re.sub("[^A-Za-z0-9]+", " ", text) # remove other than words and numbers 
    text = re.sub(" +", " ", text) # remove all extra spaces 
    text = text.strip() # remove spaces at the start and at the end 
    text = re.sub(r"http\S+", "", text) # remove links 

    return text

In [51]:
ori_df = df.copy()
df.text = df.text.apply(clean_text)
print(f"{ori_df.text.values[0]}\n{df.text.values[0]}")

Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\band of ultra-cynics, are seeing green again.
wall st bears claw back black reuters reuters short sellers wall street dwindling band ultra cynics seeing green

In [52]:
df = df.dropna(subset=["label"]) 
df.head()

                                                text  label
0  wall st bears claw back black reuters reuters ...      2
1  carlyle looks toward commercial aerospace reut...      2
2  oil economy cloud stocks outlook reuters reute...      2
3  iraq halts oil exports main southern pipeline ...      2
4  oil prices soar time record posing new menace ...      2

In [53]:
label_decoder = {
    0: "World",
    1: "Sports",
    2: "Business",
    3: "Sci/Tech"
}

In [54]:
import numpy as np 
from transformers import BertTokenizer

In [55]:
def tokenize(batch):
    tokenizer = BertTokenizer.from_pretrained("allenai/scibert_scivocab_uncased", return_dict= False)
    encoded = tokenizer(batch["text"].tolist(), return_tensors="np", padding = "longest")
    return dict(ids=encoded["input_ids"], masks=encoded["attention_mask"], targets=np.array(batch["label"]))

In [56]:
tokenize(df.head(1))

{'ids': array([[  102,  3545,   177, 23309,  3895, 30128,  1542,  3778,   144,
         13342, 30113,   144, 13342, 30113,  2001, 27316,  3545, 10833,
         10029,   484,  2123,  2102, 10186, 27637,  1081, 18934,  3755,
           103]]),
 'masks': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1]]),
 'targets': array([2])}

In [57]:
# combining all preprocessing steps into function
def preprocess(df):
    df["text"] = df.text.apply(clean_text)
    targets = tokenize(df)
    return targets

In [58]:
preprocess(df=train_df)

{'ids': array([[  102,   326,  2283, ...,     0,     0,     0],
        [  102, 19723, 15953, ...,     0,     0,     0],
        [  102,  3293,  1482, ...,     0,     0,     0],
        ...,
        [  102,   253, 17553, ...,     0,     0,     0],
        [  102, 23314, 30113, ...,     0,     0,     0],
        [  102,  3841,  2579, ...,     0,     0,     0]],
       shape=(96000, 199)),
 'masks': array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0]], shape=(96000, 199)),
 'targets': array([1, 3, 0, ..., 3, 2, 3], shape=(96000,))}